#!/bin/bash
#
# IBM Cloud Private - Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Create ReplicaSet 1 for local web werver for helm charts

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo =================================================================
echo Create ReplicaSet 1 for local web werver for helm charts
echo Create NodePort for traffic between internal and external traffic
echo =================================================================
kubectl apply -f local03.yaml
